apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  annotations:
    github.com/project-slug: appolon1908/Backstage
spec:
  type: service
  lifecycle: production
  owner: appolon-platform
  system: codestra-production
